=== BocHackathon-4-0/AskGeorge/src/ai_agent/data/balance/balance_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Account Data",
    "description": "Schema for representing account data with its balance changes over time.",
    "type": "object",
    "properties": {
        "account_number": {
            "description": "A unique identifier for the account.",
            "type": "string",
            "pattern": "^[0-9]+$"
        },
        "type": {
            "description": "The type or category of the account.",
            "type": "string",
            "enum": ["current", "savings"] 
        },
        "frequency": {
            "description": "The frequency at which the data is recorded.",
            "type": "string",
            "enum": ["daily", "weekly", "monthly"] 
        },
        "data": {
            "description": "An array containing the account's transactional data over time.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "date": {
                        "description": "The date on which the data was recorded. Format: YYYY-DD-MM.",
                        "type": "string",
                        "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
                    },
                    "amount": {
                        "description": "The total amount in the account on the given date.",
                        "type": "number"
                    },
                    "changeFromYesterday": {
                        "description": "The difference in the amount from the previous day.",
                        "type": "number"
                    },
                    "changeFromLastWeek": {
                        "description": "The difference in the amount from the previous week.",
                        "type": "number"
                    },
                    "changeFromLastMonth": {
                        "description": "The difference in the amount from the previous month.",
                        "type": "number"
                    }
                },
                "oneOf": [
                    {
                        "if": {
                            "properties": {
                                "frequency": {
                                    "const": "daily"
                                }
                            }
                        },
                        "then": {
                            "required": ["changeFromYesterday"]
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "frequency": {
                                    "const": "weekly"
                                }
                            }
                        },
                        "then": {
                            "required": ["changeFromLastWeek"]
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "frequency": {
                                    "const": "monthly"
                                }
                            }
                        },
                        "then": {
                            "required": ["changeFromLastMonth"]
                        }
                    }
                ],
                "required": ["date", "amount"]
            }
        }
    },
    "required": ["account_number", "type", "frequency", "data"]
}

=== BocHackathon-4-0/AskGeorge/src/ai_agent/data/balance/savings_monthly.json
{
    "account_number": "1234567890",
    "type": "savings",
    "frequency": "monthly",
    "data": [
        {
            "date": "2023-01-01",
            "amount": 2518.16,
            "changeFromLastMonth": 0
        },
        {
            "date": "2023-02-01",
            "amount": 3422.69,
            "changeFromLastMonth": 904.53
        },
        {
            "date": "2023-03-01",
            "amount": 4241.39,
            "changeFromLastMonth": 818.7
        },
        {
            "date": "2023-04-01",
            "amount": 5155.14,
            "changeFromLastMonth": 913.75
        },
        {
            "date": "2023-05-01",
            "amount": 6016.09,
            "changeFromLastMonth": 860.95
        },
        {
            "date": "2023-06-01",
            "amount": 6924.24,
            "changeFromLastMonth": 908.15
        },
        {
            "date": "2023-07-01",
            "amount": 7845.09,
            "changeFromLastMonth": 920.85
        },
        {
            "date": "2023-08-01",
            "amount": 8741.37,
            "changeFromLastMonth": 896.28
        },
        {
            "date": "2023-09-01",
            "amount": 9732.43,
            "changeFromLastMonth": 991.06
        },
        {
            "date": "2023-10-01",
            "amount": 10569.8,
            "changeFromLastMonth": 837.37
        }
    ]
}

=== BocHackathon-4-0/AskGeorge/src/ai_agent/data/balance/current_weekly.json
{
    "account_number": "1234567890",
    "type": "current",
    "frequency": "weekly",
    "data": [
        {
            "date": "2023-01-01",
            "amount": 411.97,
            "changeFromLastWeek": 0
        },
        {
            "date": "2023-01-08",
            "amount": 482.93,
            "changeFromLastWeek": 70.96
        },
        {
            "date": "2023-01-15",
            "amount": 576.07,
            "changeFromLastWeek": 93.14
        },
        {
            "date": "2023-01-22",
            "amount": 662.8,
            "changeFromLastWeek": 86.73
        },
        {
            "date": "2023-01-29",
            "amount": 723.94,
            "changeFromLastWeek": 61.14
        },
        {
            "date": "2023-02-05",
            "amount": 799.83,
            "changeFromLastWeek": 75.89
        },
        {
            "date": "2023-02-12",
            "amount": 873.77,
            "changeFromLastWeek": 73.94
        },
        {
            "date": "2023-02-19",
            "amount": 944.19,
            "changeFromLastWeek": 70.42
        },
        {
            "date": "2023-02-26",
            "amount": 1002.46,
            "changeFromLastWeek": 58.27
        },
        {
            "date": "2023-03-05",
            "amount": 1066.15,
            "changeFromLastWeek": 63.69
        },
        {
            "date": "2023-03-12",
            "amount": 1129.04,
            "changeFromLastWeek": 62.89
        },
        {
            "date": "2023-03-19",
            "amount": 1209.24,
            "changeFromLastWeek": 80.2
        },
        {
            "date": "2023-03-26",
            "amount": 1277.54,
            "changeFromLastWeek": 68.3
        },
        {
            "date": "2023-04-02",
            "amount": 1360.97,
            "changeFromLastWeek": 83.43
        },
        {
            "date": "2023-04-09",
            "amount": 1418.53,
            "changeFromLastWeek": 57.56
        },
        {
            "date": "2023-04-16",
            "amount": 1509.09,
            "changeFromLastWeek": 90.56
        },
        {
            "date": "2023-04-23",
            "amount": 1570.77,
            "changeFromLastWeek": 61.68
        },
        {
            "date": "2023-04-30",
            "amount": 1624.29,
            "changeFromLastWeek": 53.52
        },
        {
            "date": "2023-05-07",
            "amount": 1693.84,
            "changeFromLastWeek": 69.55
        },
        {
            "date": "2023-05-14",
            "amount": 1766.14,
            "changeFromLastWeek": 72.3
        },
        {
            "date": "2023-05-21",
            "amount": 1837.76,
            "changeFromLastWeek": 71.62
        },
        {
            "date": "2023-05-28",
            "amount": 1914.16,
            "changeFromLastWeek": 76.4
        },
        {
            "date": "2023-06-04",
            "amount": 1979.63,
            "changeFromLastWeek": 65.47
        },
        {
            "date": "2023-06-11",
            "amount": 2039.94,
            "changeFromLastWeek": 60.31
        },
        {
            "date": "2023-06-18",
            "amount": 2111.01,
            "changeFromLastWeek": 71.07
        },
        {
            "date": "2023-06-25",
            "amount": 2163.66,
            "changeFromLastWeek": 52.65
        },
        {
            "date": "2023-07-02",
            "amount": 2230.71,
            "changeFromLastWeek": 67.05
        },
        {
            "date": "2023-07-09",
            "amount": 2306.57,
            "changeFromLastWeek": 75.86
        },
        {
            "date": "2023-07-16",
            "amount": 2375.38,
            "changeFromLastWeek": 68.81
        },
        {
            "date": "2023-07-23",
            "amount": 2437.7,
            "changeFromLastWeek": 62.32
        },
        {
            "date": "2023-07-30",
            "amount": 2493.36,
            "changeFromLastWeek": 55.66
        },
        {
            "date": "2023-08-06",
            "amount": 2548.63,
            "changeFromLastWeek": 55.27
        },
        {
            "date": "2023-08-13",
            "amount": 2620.73,
            "changeFromLastWeek": 72.1
        },
        {
            "date": "2023-08-20",
            "amount": 2699.52,
            "changeFromLastWeek": 78.79
        },
        {
            "date": "2023-08-27",
            "amount": 2771.13,
            "changeFromLastWeek": 71.61
        },
        {
            "date": "2023-09-03",
            "amount": 2830.08,
            "changeFromLastWeek": 58.95
        },
        {
            "date": "2023-09-10",
            "amount": 2898.44,
            "changeFromLastWeek": 68.36
        },
        {
            "date": "2023-09-17",
            "amount": 2974.42,
            "changeFromLastWeek": 75.98
        },
        {
            "date": "2023-09-24",
            "amount": 3040.07,
            "changeFromLastWeek": 65.65
        },
        {
            "date": "2023-10-01",
            "amount": 3097.3,
            "changeFromLastWeek": 57.23
        },
        {
            "date": "2023-10-08",
            "amount": 3177.12,
            "changeFromLastWeek": 79.82
        }
    ]
}

=== BocHackathon-4-0/AskGeorge/src/ai_agent/data/balance/current_monthly.json
{
    "account_number": "1234567890",
    "type": "current",
    "frequency": "monthly",
    "data": [
        {
            "date": "2023-01-01",
            "amount": 411.97,
            "changeFromLastMonth": 0
        },
        {
            "date": "2023-02-01",
            "amount": 753.52,
            "changeFromLastMonth": 341.55
        },
        {
            "date": "2023-03-01",
            "amount": 1028.29,
            "changeFromLastMonth": 274.77
        },
        {
            "date": "2023-04-01",
            "amount": 1349.06,
            "changeFromLastMonth": 320.77
        },
        {
            "date": "2023-05-01",
            "amount": 1634.89,
            "changeFromLastMonth": 285.83
        },
        {
            "date": "2023-06-01",
            "amount": 1950.69,
            "changeFromLastMonth": 315.8
        },
        {
            "date": "2023-07-01",
            "amount": 2223.61,
            "changeFromLastMonth": 272.92
        },
        {
            "date": "2023-08-01",
            "amount": 2506.37,
            "changeFromLastMonth": 282.76
        },
        {
            "date": "2023-09-01",
            "amount": 2810.03,
            "changeFromLastMonth": 303.66
        },
        {
            "date": "2023-10-01",
            "amount": 3097.3,
            "changeFromLastMonth": 287.27
        }
    ]
}

=== BocHackathon-4-0/AskGeorge/src/ai_agent/data/balance/savings_weekly.json
{
    "account_number": "1234567890",
    "type": "savings",
    "frequency": "weekly",
    "data": [
        {
            "date": "2023-01-01",
            "amount": 2518.16,
            "changeFromLastWeek": 0
        },
        {
            "date": "2023-01-08",
            "amount": 2722.5,
            "changeFromLastWeek": 204.34
        },
        {
            "date": "2023-01-15",
            "amount": 2914.01,
            "changeFromLastWeek": 191.51
        },
        {
            "date": "2023-01-22",
            "amount": 3136.86,
            "changeFromLastWeek": 222.85
        },
        {
            "date": "2023-01-29",
            "amount": 3341.11,
            "changeFromLastWeek": 204.25
        },
        {
            "date": "2023-02-05",
            "amount": 3552.04,
            "changeFromLastWeek": 210.93
        },
        {
            "date": "2023-02-12",
            "amount": 3762.79,
            "changeFromLastWeek": 210.75
        },
        {
            "date": "2023-02-19",
            "amount": 3953.16,
            "changeFromLastWeek": 190.37
        },
        {
            "date": "2023-02-26",
            "amount": 4138.25,
            "changeFromLastWeek": 185.09
        },
        {
            "date": "2023-03-05",
            "amount": 4347.11,
            "changeFromLastWeek": 208.86
        },
        {
            "date": "2023-03-12",
            "amount": 4561.53,
            "changeFromLastWeek": 214.42
        },
        {
            "date": "2023-03-19",
            "amount": 4770.67,
            "changeFromLastWeek": 209.14
        },
        {
            "date": "2023-03-26",
            "amount": 4976.34,
            "changeFromLastWeek": 205.67
        },
        {
            "date": "2023-04-02",
            "amount": 5180.93,
            "changeFromLastWeek": 204.59
        },
        {
            "date": "2023-04-09",
            "amount": 5392.64,
            "changeFromLastWeek": 211.71
        },
        {
            "date": "2023-04-16",
            "amount": 5605.58,
            "changeFromLastWeek": 212.94
        },
        {
            "date": "2023-04-23",
            "amount": 5820.33,
            "changeFromLastWeek": 214.75
        },
        {
            "date": "2023-04-30",
            "amount": 5997.95,
            "changeFromLastWeek": 177.62
        },
        {
            "date": "2023-05-07",
            "amount": 6187.23,
            "changeFromLastWeek": 189.28
        },
        {
            "date": "2023-05-14",
            "amount": 6386.16,
            "changeFromLastWeek": 198.93
        },
        {
            "date": "2023-05-21",
            "amount": 6606.79,
            "changeFromLastWeek": 220.63
        },
        {
            "date": "2023-05-28",
            "amount": 6804.25,
            "changeFromLastWeek": 197.46
        },
        {
            "date": "2023-06-04",
            "amount": 7020.11,
            "changeFromLastWeek": 215.86
        },
        {
            "date": "2023-06-11",
            "amount": 7240.33,
            "changeFromLastWeek": 220.22
        },
        {
            "date": "2023-06-18",
            "amount": 7434.96,
            "changeFromLastWeek": 194.63
        },
        {
            "date": "2023-06-25",
            "amount": 7647.66,
            "changeFromLastWeek": 212.7
        },
        {
            "date": "2023-07-02",
            "amount": 7864.71,
            "changeFromLastWeek": 217.05
        },
        {
            "date": "2023-07-09",
            "amount": 8077.36,
            "changeFromLastWeek": 212.65
        },
        {
            "date": "2023-07-16",
            "amount": 8293.34,
            "changeFromLastWeek": 215.98
        },
        {
            "date": "2023-07-23",
            "amount": 8498.7,
            "changeFromLastWeek": 205.36
        },
        {
            "date": "2023-07-30",
            "amount": 8693.33,
            "changeFromLastWeek": 194.63
        },
        {
            "date": "2023-08-06",
            "amount": 8888.01,
            "changeFromLastWeek": 194.68
        },
        {
            "date": "2023-08-13",
            "amount": 9086.73,
            "changeFromLastWeek": 198.72
        },
        {
            "date": "2023-08-20",
            "amount": 9315.46,
            "changeFromLastWeek": 228.73
        },
        {
            "date": "2023-08-27",
            "amount": 9566.29,
            "changeFromLastWeek": 250.83
        },
        {
            "date": "2023-09-03",
            "amount": 9788.78,
            "changeFromLastWeek": 222.49
        },
        {
            "date": "2023-09-10",
            "amount": 10014.16,
            "changeFromLastWeek": 225.38
        },
        {
            "date": "2023-09-17",
            "amount": 10201.54,
            "changeFromLastWeek": 187.38
        },
        {
            "date": "2023-09-24",
            "amount": 10397.38,
            "changeFromLastWeek": 195.84
        },
        {
            "date": "2023-10-01",
            "amount": 10569.8,
            "changeFromLastWeek": 172.42
        },
        {
            "date": "2023-10-08",
            "amount": 10791.55,
            "changeFromLastWeek": 221.75
        }
    ]
}
